### ISSUE TITLE
No limits on bounds of random numbers (especially count!)

### ISSUE THREAD

**Issue by sharmavins23** [18maherc/Discord-Bot#3]
https://github.com/18maherc/Discord-Bot/blob/731a0835cffdac7f4a7aa800bfb2101d150ad726/src/randomness.py#L12

An adequately large count ensures a guaranteed crash of Heroku services and permits a free denial of service attack.

**Comment by sharmavins23** [comment]
This issue has been fixed, but needs a check for the lower bound being higher than the upper bound.

**Comment by sharmavins23** [comment]
This also fails with decimal values.

**Comment by 18maherc** [comment]
fixed
